# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    annotations: false
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
<<<<<<< HEAD
        enabled: true
=======
        enabled : true
>>>>>>> 934c314924fad945bb73f051126fbd4564a29d9c
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    mailer:
        dsn: '%env(MAILER_DSN)'

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file


#translator
    default_locale: '%env(DEFAULT_LOCALE)%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            ['fr','en'] # Langue de repli en cas d'absence de traduction
