controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

accueil:
    path: /{_locale}/
    controller: App\Controller\AccueilController::index
    requirements:
        _locale: 'fr|en' # Cela spécifie que seules ces langues sont valides
    defaults: {_locale : fr } # Définit 'fr' comme langue par défaut

app_home_redirect:
    path: /
    controller: App\Controller\AccueilController::redirectToDefaultLanguage

# config/routes.yaml
switch_language:
    path: /switch-language/{_locale}
    controller: App\Controller\LanguageController::switchLanguage
    requirements:
        _locale: 'en|fr'  # Langues acceptées

# Redirection vers reservation avec la langue par défaut 'fr'
app_reservation:
    path: /{_locale}/reservation
    controller: App\Controller\ReservationController::index
    requirements:
        _locale: en|fr

redirect_to_locale:
    path: /reservation
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_reservation
        permanent: true
        _locale: fr  # la langue par défaut

# Redirection vers le gîte avec la langue par défaut 'fr'
redirect_to_gite:
    path: /notre-gite
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_gite
        permanent: true
        _locale: fr  # redirection vers la version française du gîte

# Route pour le gîte en différentes langues
app_gite:
    path: /{_locale}/notre-gite
    controller: App\Controller\AccueilController::index
    requirements:
        _locale: en|fr

# Redirection vers tourisme avec la langue par défaut 'fr'
redirect_to_tourisme:
    path: /tourisme
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_tourisme
        permanent: true
        _locale: fr  # redirection vers la version française du gîte

# Route pour tourisme en différentes langues
app_tourisme:
    path: /{_locale}/tourisme
    controller: App\Controller\AccueilController::index
    requirements:
        _locale: en|fr

# Redirection vers le tourisme avec la langue par défaut 'fr'
redirect_to_magazine:
    path: /magazine
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_magazine
        permanent: true
        _locale: fr  # redirection vers la version française du gîte

# Route pour le gîte en différentes langues
app_magazine:
    path: /{_locale}/magazine
    controller: App\Controller\AccueilController::index
    requirements:
        _locale: en|fr

