controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
sitemap:
    path: /sitemap.xml
    controller: App\Controller\SitemapController::index
